"use client";

import React, { useState } from 'react';
import { useSession } from "next-auth/react";

export default function StudyHub({ exam = "General", level = "Intermediate" }) {
  const { data: session } = useSession();
  const [activeNotes, setActiveNotes] = useState<string | null>(null);
  const [isGenerating, setIsGenerating] = useState(false);
  const [selectedTopic, setSelectedTopic] = useState("");

  // Simulated Personalized Path based on Exam
// 🚀 THE FIX: Dynamic Learning Path Generator
  const learningPath = React.useMemo(() => {
    const examLower = exam.toLowerCase();
    let topics = [];

    // Catch variations of Class 12 / High School
    if (examLower.includes("12") || examLower.includes("board") || examLower.includes("high school")) {
      topics = ["Electromagnetism", "Optics & Light", "Modern Physics"];
    } 
    // Catch variations of GATE / CS / B.Tech
    else if (examLower.includes("gate") || examLower.includes("cs") || examLower.includes("b.tech")) {
      topics = ["Advanced Data Structures", "Operating Systems Memory", "System Design Basics"];
    } 
    // Catch variations of UPSC / Civil Services
    else if (examLower.includes("upsc") || examLower.includes("civil")) {
      topics = ["Indian Polity", "Macroeconomics", "World Geography"];
    } 
    // Catch variations of JEE / Medical
    else if (examLower.includes("jee") || examLower.includes("neet")) {
      topics = ["Rotational Mechanics", "Organic Chemistry", "Integral Calculus"];
    } 
    // ULTIMATE FAILSAFE: If they type a random subject, dynamically build the titles!
    else {
      topics = [`${exam} Fundamentals`, `Advanced ${exam} Concepts`, `${exam} Mastery`];
    }

    return [
      { id: 1, topic: topics[0], status: "completed" },
      { id: 2, topic: topics[1], status: "current" },
      { id: 3, topic: topics[2], status: "locked" },
    ];
  }, [exam]);

  const handleGenerateNotes = async (topic: string) => {
    setSelectedTopic(topic);
    setIsGenerating(true);
    setActiveNotes(null);

    try {
      const res = await fetch("http://127.0.0.1:8000/api/v1/generate-notes", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ topic, exam, level }),
      });
      const data = await res.json();
      setActiveNotes(data.notes);
    } catch (error) {
      setActiveNotes("⚠️ Could not connect to the AI Engine. Please try again.");
    } finally {
      setIsGenerating(false);
    }
  };

  // 🚀 THE NEW PDF EXPORT ENGINE
// 🚀 THE UPGRADED NATIVE PDF EXPORT ENGINE (Bypasses CSS entirely)
  const handleDownloadPDF = async () => {
    try {
      // Dynamically import to prevent Next.js server-side crashes
      const { jsPDF } = await import('jspdf');
      const doc = new jsPDF();

      // 1. Add the Title
      doc.setFont("helvetica", "bold");
      doc.setFontSize(22);
      doc.setTextColor(15, 23, 42); // Dark Slate color
      doc.text(`${selectedTopic}`, 20, 20);
      
      // 2. Add a decorative divider line
      doc.setDrawColor(203, 213, 225); 
      doc.line(20, 25, 190, 25);

      // 3. Add the actual AI Notes (Split into wrapped lines to fit the page)
      doc.setFont("helvetica", "normal");
      doc.setFontSize(12);
      doc.setTextColor(51, 65, 85); // Professional Gray
      
      // Calculate text wrapping (170mm is the safe width area)
      const splitText = doc.splitTextToSize(activeNotes || "", 170);
      doc.text(splitText, 20, 35);

      // 4. Add the Startup Watermark at the bottom
      const pageHeight = doc.internal.pageSize.height;
      doc.setFont("helvetica", "italic");
      doc.setFontSize(10);
      doc.setTextColor(148, 163, 184);
      doc.text("Generated by Cognitive Edu Engine", 20, pageHeight - 10);

      // 5. Trigger the download
      doc.save(`${selectedTopic.replace(/\s+/g, '_')}_Notes.pdf`);
      
    } catch (error) {
      console.error("PDF Generation failed:", error);
    }
  };

  return (
    <div className="bg-slate-900 border border-slate-800 rounded-2xl p-6 shadow-xl relative overflow-hidden">
      
      {/* HEADER */}
      <div className="flex justify-between items-center mb-6">
        <h2 className="text-2xl font-bold text-white flex items-center gap-2">
          <span className="text-emerald-400">⚡</span> Study Hub & Analytics
        </h2>
        <span className="bg-slate-800 text-slate-300 text-xs px-3 py-1 rounded-full border border-slate-700">
          Target: {exam}
        </span>
      </div>

      {/* PERFORMANCE METRICS */}
      <div className="grid grid-cols-3 gap-4 mb-8">
        <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
          <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">Knowledge Retention</p>
          <div className="text-3xl font-black text-white">78<span className="text-lg text-emerald-400">%</span></div>
          <div className="w-full bg-slate-700 h-1.5 rounded-full mt-2"><div className="bg-emerald-400 h-1.5 rounded-full w-[78%]"></div></div>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
          <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">Concepts Mastered</p>
          <div className="text-3xl font-black text-white">12<span className="text-lg text-slate-500">/45</span></div>
          <p className="text-emerald-400 text-xs mt-1 font-medium">↑ 3 this week</p>
        </div>
        <div className="bg-slate-800/50 rounded-xl p-4 border border-slate-700/50">
          <p className="text-slate-400 text-xs font-semibold uppercase tracking-wider mb-1">AI Focus Prediction</p>
          <div className="text-sm font-bold text-cyan-400 mt-2 truncate">
            Needs work on: {learningPath[1].topic}
          </div>
        </div>
      </div>

      {/* PERSONALIZED LEARNING PATH */}
      <div>
        <h3 className="text-lg font-bold text-white mb-4">Your Dynamic Learning Path</h3>
        <div className="space-y-4 relative before:absolute before:inset-0 before:ml-5 before:-translate-x-px md:before:mx-auto md:before:translate-x-0 before:h-full before:w-0.5 before:bg-gradient-to-b before:from-transparent before:via-slate-700 before:to-transparent">
          
          {learningPath.map((item, index) => (
            <div key={item.id} className="relative flex items-center justify-between md:justify-normal md:odd:flex-row-reverse group is-active">
              <div className={`flex items-center justify-center w-10 h-10 rounded-full border-4 border-slate-900 shrink-0 md:order-1 md:group-odd:-translate-x-1/2 md:group-even:translate-x-1/2 shadow flex-col ${item.status === 'completed' ? 'bg-emerald-500' : item.status === 'current' ? 'bg-cyan-500 animate-pulse' : 'bg-slate-700'}`}>
                <span className="text-white text-xs font-bold">{index + 1}</span>
              </div>
              <div className="w-[calc(100%-4rem)] md:w-[calc(50%-2.5rem)] bg-slate-800/80 p-4 rounded-xl border border-slate-700 shadow-lg flex justify-between items-center">
                <div>
                  <h4 className={`font-bold ${item.status === 'locked' ? 'text-slate-500' : 'text-slate-200'}`}>{item.topic}</h4>
                  <p className="text-xs text-slate-400 capitalize">{item.status}</p>
                </div>
                
                {item.status !== 'locked' && (
                  <button 
                    onClick={() => handleGenerateNotes(item.topic)}
                    className="bg-indigo-600 hover:bg-indigo-500 text-white text-xs font-bold py-2 px-3 rounded-lg transition-all shadow-[0_0_15px_rgba(79,70,229,0.3)]"
                  >
                    AI Notes ✨
                  </button>
                )}
              </div>
            </div>
          ))}

        </div>
      </div>

      {/* AI NOTES MODAL */}
      {(isGenerating || activeNotes) && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 backdrop-blur-sm p-4">
          <div className="bg-slate-900 border border-slate-700 rounded-2xl w-full max-w-2xl max-h-[80vh] flex flex-col shadow-2xl">
            
            {/* MODAL HEADER */}
            <div className="bg-slate-900/90 backdrop-blur border-b border-slate-800 p-4 flex justify-between items-center rounded-t-2xl">
              <h3 className="text-xl font-bold text-white flex items-center gap-2">
                <span className="text-indigo-400">✨</span> AI Notes: {selectedTopic}
              </h3>
              
              <div className="flex items-center gap-3">
                {/* 📥 DOWNLOAD BUTTON (Only shows if notes are generated) */}
                {!isGenerating && activeNotes && (
                  <button 
                    onClick={handleDownloadPDF}
                    className="bg-emerald-600 hover:bg-emerald-500 text-white text-xs font-bold py-1.5 px-3 rounded-md transition-all shadow-lg flex items-center gap-1"
                  >
                    📥 Download PDF
                  </button>
                )}
                <button onClick={() => {setIsGenerating(false); setActiveNotes(null);}} className="text-slate-400 hover:text-white font-bold text-2xl leading-none">&times;</button>
              </div>
            </div>

            {/* MODAL CONTENT (This is the section the PDF engine captures) */}
            <div className="p-6 overflow-y-auto bg-slate-900 rounded-b-2xl">
              {isGenerating ? (
                <div className="flex flex-col items-center justify-center py-12">
                  <div className="w-8 h-8 border-4 border-indigo-500 border-t-transparent rounded-full animate-spin mb-4"></div>
                  <p className="text-indigo-400 animate-pulse font-semibold">Gemini is synthesizing high-yield notes...</p>
                </div>
              ) : (
                <div id="ai-notes-content" className="prose prose-invert prose-emerald max-w-none p-4 bg-slate-900 text-slate-300">
                  {/* We added a title specifically for the PDF document */}
                  <h1 className="text-3xl font-black mb-6 border-b border-slate-700 pb-4">{selectedTopic}</h1>
                  {activeNotes}
                  
                  {/* Watermark for the PDF */}
                  <div className="mt-12 pt-4 border-t border-slate-800 text-center text-xs text-slate-500 font-mono">
                    Generated by Cognitive Edu Engine
                  </div>
                </div>
              )}
            </div>

          </div>
        </div>
      )}

    </div>
  );
}